In [2]:
import pandas as pd
from geopy.geocoders import Nominatim
from time import sleep

In [3]:
#Loading the Bird Strikes data as Pandas dataframe

file_path = r"F:\UM Internship\Bird Strikes Visualization\Bird Strikes data cleaned.xlsx"
dataset = pd.read_excel(file_path)

In [50]:
dataset

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,238459,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,CL-RJ100/200,11 to 100,70,NaN,2006-02-02,No damage,...,False,ATIS WARNING. PILOT REPTD STRIKE TO ATCT. COUN...,Small,Overcast,European starling,Y,0,150,0,No
1,254001,Airplane,ADAMS FIELD ARPT,< 1000 ft,B-737-300,11 to 100,69,NaN,2008-07-03,No damage,...,False,NO DMG.,Small,Some Cloud,Unknown bird - small,N,0,0,0,Yes
2,252465,Airplane,ADAMS FIELD ARPT,> 1000 ft,A-300,11 to 100,66,NaN,2007-11-05,No damage,...,True,"ID BY SMITHSONIAN, FAA 2214. CLEANED & INSPCTD...",Small,Some Cloud,Dark-eyed junco,N,0,1800,0,No
3,258334,Airplane,ADAMS FIELD ARPT,< 1000 ft,A-320,11 to 100,65,NaN,2008-07-03,No damage,...,False,DURING LANDING FLARE AND TOUCHDOWN A/C HIT SEV...,Small,Some Cloud,Purple martin,N,0,0,0,No
4,248908,Airplane,ADAMS FIELD ARPT,< 1000 ft,EMB-145,11 to 100,38,Precautionary Landing,2007-07-27,No damage,...,False,12 FEMALE PURPLE MARTINS COLLECTED. NO DMG. MA...,Small,Some Cloud,Purple martin,N,0,10,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25424,319672,Airplane,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,NaN,2011-12-29,No damage,...,True,ID BY SMITHSONIAN. SAMPLES FROM BOTH A/C AND B...,Medium,No Cloud,Mallard,Y,0,10,0,Yes
25425,321151,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,NaN,2011-12-30,No damage,...,False,DUCK? NO DMG REPTD.,Large,Overcast,Unknown bird - large,N,0,1500,0,No
25426,319677,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,NaN,2011-12-30,No damage,...,False,NaN,Small,Some Cloud,Tree swallow,Y,0,0,0,No
25427,319679,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,NaN,2011-12-31,No damage,...,False,PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...,Medium,Some Cloud,Unknown bird - medium,Y,0,0,0,Yes
25428,319593,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,NaN,2011-12-31,Caused damage,...,False,"HIT CENTER OF RADOME, CAVING IN ABOUT 12"". RAD...",Medium,No Cloud,Red-tailed hawk,N,0,0,0,Yes

In [5]:
dataset.columns

Index(['Record ID', 'Aircraft: Type', 'Airport: Name', 'Altitude bin',
       'Aircraft: Make/Model', 'Wildlife: Number struck',
       'Wildlife: Number Struck Actual', 'Effect: Impact to flight',
       'FlightDate', 'Effect: Indicated Damage',
       'Aircraft: Number of engines?', 'Aircraft: Airline/Operator',
       'Origin State', 'When: Phase of flight', 'Conditions: Precipitation',
       'Remains of wildlife collected?',
       'Remains of wildlife sent to Smithsonian', 'Remarks', 'Wildlife: Size',
       'Conditions: Sky', 'Wildlife: Species',
       'Pilot warned of birds or wildlife?', 'Cost: Total $',
       'Feet above ground', 'Number of people injured', 'Is Aircraft Large?'],
      dtype='object')

In [8]:
#Grouping by airports with SUM aggregate to get the total no. of bird strikes for each unique airport

airport_grouped = dataset.groupby('Airport: Name').agg({'Wildlife: Number Struck Actual':'sum'})

In [51]:
airport_grouped

                              Wildlife: Number Struck Actual
Airport: Name
ABERDEEN REGIONAL AR                                      31
ABILENE REGIONAL ARPT                                     14
ABRAHAM LINCOLN CAPITAL ARPT                             119
ADAMS COUNTY- LEGION FIELD                                 4
ADAMS FIELD ARPT                                         333
...                                                      ...
YELLOWSTONE REGIONAL                                      16
YOUNGSTOWN-WARREN RGNL ARPT                                7
ZAMPERINI FIELD ARPT                                       1
ZELIENOPLE MUNICIPAL                                      10
ZURICH                                                     1

[1109 rows x 1 columns]

In [10]:
airport_grouped_reset = airport_grouped.reset_index()

In [52]:
airport_grouped_reset

                     Airport: Name  Wildlife: Number Struck Actual
0             ABERDEEN REGIONAL AR                              31
1            ABILENE REGIONAL ARPT                              14
2     ABRAHAM LINCOLN CAPITAL ARPT                             119
3       ADAMS COUNTY- LEGION FIELD                               4
4                 ADAMS FIELD ARPT                             333
...                            ...                             ...
1104          YELLOWSTONE REGIONAL                              16
1105   YOUNGSTOWN-WARREN RGNL ARPT                               7
1106          ZAMPERINI FIELD ARPT                               1
1107          ZELIENOPLE MUNICIPAL                              10
1108                        ZURICH                               1

[1109 rows x 2 columns]

In [12]:
#Sorting the airports in descending order of no. of bird strikes 

airport_group_sort = airport_grouped_reset.sort_values(by='Wildlife: Number Struck Actual', ascending=False)

In [53]:
airport_group_sort

                    Airport: Name  Wildlife: Number Struck Actual
208   DALLAS/FORT WORTH INTL ARPT                            2933
875               SACRAMENTO INTL                            1856
530                  LAGUARDIA NY                            1579
783             PHILADELPHIA INTL                            1396
882           SALT LAKE CITY INTL                            1376
...                           ...                             ...
387        GRIFFING SANDUSKY ARPT                               1
889             SAN SALVADOR INTL                               1
612       MARIANNA MUNICIPAL ARPT                               1
611               MARCO POLO INTL                               1
1108                       ZURICH                               1

[1109 rows x 2 columns]

In [14]:
airport_group_sort.value_counts('Wildlife: Number Struck Actual')

Wildlife: Number Struck Actual
1       315
2       128
3        63
4        44
5        35
       ...
143       1
142       1
141       1
138       1
2933      1
Name: count, Length: 202, dtype: int64

In [54]:
#Filtering the data to get airports with 10 and above bird strikes

TenAndAboveStrikes = airport_group_sort[airport_group_sort['Wildlife: Number Struck Actual'] >= 10]

In [55]:
TenAndAboveStrikes

                             Airport: Name  Wildlife: Number Struck Actual
208            DALLAS/FORT WORTH INTL ARPT                            2933
875                        SACRAMENTO INTL                            1856
530                           LAGUARDIA NY                            1579
783                      PHILADELPHIA INTL                            1396
882                    SALT LAKE CITY INTL                            1376
...                                    ...                             ...
890                        SAND POINT ARPT                              10
549         LAWTON-FORT SILL REGIONAL ARPT                              10
679   MONTREAL/PIERRE-ELLIOTT-TRUDEAU INTL                              10
1085            WILLIAMSON COUNTY REGIONAL                              10
188                  CONCORD REGIONAL ARPT                              10

[410 rows x 2 columns]

In [56]:
TenAndAboveStrikes = TenAndAboveStrikes.reset_index(drop=True)

In [57]:
TenAndAboveStrikes

                            Airport: Name  Wildlife: Number Struck Actual
0             DALLAS/FORT WORTH INTL ARPT                            2933
1                         SACRAMENTO INTL                            1856
2                            LAGUARDIA NY                            1579
3                       PHILADELPHIA INTL                            1396
4                     SALT LAKE CITY INTL                            1376
..                                    ...                             ...
405                       SAND POINT ARPT                              10
406        LAWTON-FORT SILL REGIONAL ARPT                              10
407  MONTREAL/PIERRE-ELLIOTT-TRUDEAU INTL                              10
408            WILLIAMSON COUNTY REGIONAL                              10
409                 CONCORD REGIONAL ARPT                              10

[410 rows x 2 columns]

In [58]:
#Function to perform some data cleaning with string function 'replace', to prepare the data for geocoding 

def edit_airport(airport):
    airport = airport.replace('INTL', 'INTERNATIONAL').replace('ARPT', 'AIRPORT')
    if 'AIRPORT' not in airport:
        airport += ' AIRPORT'
    return airport

In [59]:
#Applying the function on the filtered data

TenAndAboveStrikes['Airport: Name'] = TenAndAboveStrikes['Airport: Name'].apply(edit_airport)

In [60]:
TenAndAboveStrikes

,Airport: Name,Wildlife: Number Struck Actual
0,DALLAS/FORT WORTH INTERNATIONAL AIRPORT,2933
1,SACRAMENTO INTERNATIONAL AIRPORT,1856
2,LAGUARDIA NY AIRPORT,1579
3,PHILADELPHIA INTERNATIONAL AIRPORT,1396
4,SALT LAKE CITY INTERNATIONAL AIRPORT,1376
...,...,...
405,SAND POINT AIRPORT,10
406,LAWTON-FORT SILL REGIONAL AIRPORT,10
407,MONTREAL/PIERRE-ELLIOTT-TRUDEAU INTERNATIONAL ...,10
408,WILLIAMSON COUNTY REGIONAL AIRPORT,10
409,CONCORD REGIONAL AIRPORT,10

In [61]:
#Function to perform geocoding using the Nominatim geocoder of geopy library.
#This function will take an airport name as input and return its coordinates (latitude and longitude) as output.
#Using sleep function of time library, a time delay of 1 second has been put after every geocoding API call.

#For airports that could not be geocoded, 'NA' values are returned.
#Names of such airports have been further cleaned by cross-checking from the internet;
#then the data has been updated with the corrected airport names, and again geocoded with this function successfully


def get_coordinates(airports):
    geolocator = Nominatim(user_agent='')
    airport_lat, airport_long = [], []
    for a in airports:
        location = geolocator.geocode(a)
        if location:
            airport_lat.append(location.latitude)
            airport_long.append(location.longitude)
        else:
            airport_lat.append('NA')
            airport_long.append('NA')
        sleep(1)
    return (airport_lat, airport_long)

In [62]:
TenAndAboveStrikes['Wildlife: Number Struck Actual'].unique()

array([2933, 1856, 1579, 1396, 1376, 1210, 1207, 1181, 1119, 1027, 1003,
        962,  921,  917,  915,  914,  897,  880,  855,  845,  826,  775,
        752,  742,  731,  659,  626,  623,  613,  605,  578,  571,  559,
        557,  542,  530,  514,  508,  481,  474,  466,  460,  455,  453,
        445,  431,  421,  417,  409,  404,  402,  400,  388,  366,  360,
        359,  349,  346,  341,  333,  326,  315,  308,  300,  288,  284,
        283,  277,  270,  269,  268,  265,  257,  251,  237,  227,  207,
        200,  199,  198,  196,  190,  188,  187,  183,  180,  174,  170,
        165,  163,  161,  160,  157,  156,  150,  145,  143,  142,  141,
        138,  135,  133,  128,  127,  122,  121,  119,  118,  117,  113,
        112,  111,  109,  107,  106,  105,  103,  101,  100,   98,   97,
         96,   95,   94,   93,   92,   90,   89,   86,   84,   81,   80,
         76,   75,   74,   73,   72,   71,   70,   69,   68,   67,   66,
         65,   64,   62,   60,   58,   57,   55,   54,   53,   52,   51,
         50,   48,   47,   46,   45,   44,   42,   41,   40,   39,   38,
         37,   36,   35,   34,   33,   32,   31,   30,   29,   28,   27,
         26,   25,   24,   23,   22,   21,   20,   19,   18,   17,   16,
         15,   14,   13,   12,   11,   10], dtype=int64)

In [74]:
#Filtering the '10 and above strikes' dataframe to get airports with 1000 and above bird strikes

ThousandAndAboveStrikes = TenAndAboveStrikes[TenAndAboveStrikes['Wildlife: Number Struck Actual'] >= 1000]

In [75]:
ThousandAndAboveStrikes

                              Airport: Name  Wildlife: Number Struck Actual
0   DALLAS/FORT WORTH INTERNATIONAL AIRPORT                            2933
1          SACRAMENTO INTERNATIONAL AIRPORT                            1856
2                      LAGUARDIA NY AIRPORT                            1579
3        PHILADELPHIA INTERNATIONAL AIRPORT                            1396
4      SALT LAKE CITY INTERNATIONAL AIRPORT                            1376
5       SAN FRANCISCO INTERNATIONAL AIRPORT                            1210
6      JOHN F KENNEDY INTERNATIONAL AIRPORT                            1207
7      SEATTLE-TACOMA INTERNATIONAL AIRPORT                            1181
8             NORFOLK INTERNATIONAL AIRPORT                            1119
9      BALTIMORE WASH INTERNATIONAL AIRPORT                            1027
10          NASHVILLE INTERNATIONAL AIRPORT                            1003

In [76]:
#Cleaning airport names for successful geocoding

ThousandAndAboveStrikes.loc[2, 'Airport: Name'] = ThousandAndAboveStrikes.loc[2, 'Airport: Name'].replace('NY', 'NEW YORK')
ThousandAndAboveStrikes.loc[9, 'Airport: Name'] = ThousandAndAboveStrikes.loc[9, 'Airport: Name'].replace('WASH', 'WASHINGTON')

In [78]:
ThousandAndAboveStrikes

                                 Airport: Name  Wildlife: Number Struck Actual
0      DALLAS/FORT WORTH INTERNATIONAL AIRPORT                            2933
1             SACRAMENTO INTERNATIONAL AIRPORT                            1856
2                   LAGUARDIA NEW YORK AIRPORT                            1579
3           PHILADELPHIA INTERNATIONAL AIRPORT                            1396
4         SALT LAKE CITY INTERNATIONAL AIRPORT                            1376
5          SAN FRANCISCO INTERNATIONAL AIRPORT                            1210
6         JOHN F KENNEDY INTERNATIONAL AIRPORT                            1207
7         SEATTLE-TACOMA INTERNATIONAL AIRPORT                            1181
8                NORFOLK INTERNATIONAL AIRPORT                            1119
9   BALTIMORE WASHINGTON INTERNATIONAL AIRPORT                            1027
10             NASHVILLE INTERNATIONAL AIRPORT                            1003

In [79]:
#Getting the airport coordinates for '1000 and above strikes' data using the geocoding function

lat_1000, long_1000 = get_coordinates(ThousandAndAboveStrikes['Airport: Name'])

In [84]:
#Adding the obtained coordinates to the dataframe by creating new columns for latitudes and longitudes

ThousandAndAboveStrikes.loc[:, 'latitude'] = lat_1000
ThousandAndAboveStrikes.loc[:, 'longitude'] = long_1000

In [86]:
ThousandAndAboveStrikes

,Airport: Name,Wildlife: Number Struck Actual,latitude,longitude
0,DALLAS/FORT WORTH INTERNATIONAL AIRPORT,2933,32.896519,-97.046522
1,SACRAMENTO INTERNATIONAL AIRPORT,1856,38.687223,-121.590370
2,LAGUARDIA NEW YORK AIRPORT,1579,40.770357,-73.869953
3,PHILADELPHIA INTERNATIONAL AIRPORT,1396,39.875018,-75.235213
4,SALT LAKE CITY INTERNATIONAL AIRPORT,1376,40.790066,-111.979898
5,SAN FRANCISCO INTERNATIONAL AIRPORT,1210,37.622452,-122.383989
6,JOHN F KENNEDY INTERNATIONAL AIRPORT,1207,40.642948,-73.779373
7,SEATTLE-TACOMA INTERNATIONAL AIRPORT,1181,47.447567,-122.308016
8,NORFOLK INTERNATIONAL AIRPORT,1119,36.894670,-76.202296
9,BALTIMORE WASHINGTON INTERNATIONAL AIRPORT,1027,39.174720,-76.670755
10,NASHVILLE INTERNATIONAL AIRPORT,1003,36.119590,-86.683087

In [87]:
#Saving the '1000 and above strikes' data as MS Excel file

ThousandAndAboveStrikes.to_excel(r"F:\UM Internship\Bird Strikes Visualization\1000AndAboveStrikes.xlsx")

In [88]:
#Filtering the '10 and above strikes' dataframe to get airports with 500 to 1000 bird strikes

strikes500to1000 = TenAndAboveStrikes[(TenAndAboveStrikes['Wildlife: Number Struck Actual'] >= 500) & (TenAndAboveStrikes['Wildlife: Number Struck Actual'] < 1000)]

In [89]:
strikes500to1000

,Airport: Name,Wildlife: Number Struck Actual
11,LOGAN INTERNATIONAL AIRPORT,962
12,KANSAS CITY INTERNATIONAL AIRPORT,921
13,CHARLOTTE/DOUGLAS INTERNATIONAL AIRPORT,917
14,CINCINNATI/NORTHERN KENTUCKY INTERNATIONAL AIR...,915
15,LOUISVILLE INTERNATIONAL AIRPORT,914
16,ATLANTA INTERNATIONAL AIRPORT,897
17,NEWARK LIBERTY INTERNATIONAL AIRPORT,880
18,ORLANDO INTERNATIONAL AIRPORT,855
19,DENVER INTERNATIONAL AIRPORT,845
20,WASHINGTON DULLES INTERNATIONAL AIRPORT,826
21,METRO OAKLAND INTERNATIONAL AIRPORT,775
22,CHICAGO O'HARE INTERNATIONAL AIRPORT,752
23,CLEVELAND-HOPKINS INTERNATIONAL AIRPORT,742
24,HARRISBURG INTERNATIONAL AIRPORT,731
25,LAMBERT-ST LOUIS INTERNATIONAL AIRPORT,659
26,DETROIT METRO WAYNE COUNTY AIRPORT,626
27,GREATER PITTSBURGH AIRPORT,623
28,LIHUE AIRPORT,613
29,BIRMINGHAM-SHUTTLESWORTH INTERNATIONAL AIRPORT,605
30,CHICAGO MIDWAY INTERNATIONAL AIRPORT,578
31,EPPLEY AIRFIELD AIRPORT,571
32,RONALD REAGAN WASHINGTON NATL AIRPORT,559
33,MINNEAPOLIS-ST PAUL INTERNATIONAL AIRPORT,557
34,GUAYAQUIL/S BOLIVAR AIRPORT,542
35,LOS ANGELES INTERNATIONAL AIRPORT,530
36,MEMPHIS INTERNATIONAL AIRPORT,514
37,PORTLAND INTERNATIONAL (OR) AIRPORT,508

In [90]:
#Cleaning airport names for successful geocoding

strikes500to1000.loc[21, 'Airport: Name'] = strikes500to1000.loc[21, 'Airport: Name'].replace('METRO', 'METROPOLITAN')
strikes500to1000.loc[26, 'Airport: Name'] = strikes500to1000.loc[26, 'Airport: Name'].replace('METRO', 'METROPOLITAN')
strikes500to1000.loc[32, 'Airport: Name'] = strikes500to1000.loc[32, 'Airport: Name'].replace('NATL', 'NATIONAL')
strikes500to1000.loc[34, 'Airport: Name'] = strikes500to1000.loc[34, 'Airport: Name'].replace('GUAYAQUIL/S', 'SIMON')

In [94]:
strikes500to1000

,Airport: Name,Wildlife: Number Struck Actual
11,LOGAN INTERNATIONAL AIRPORT,962
12,KANSAS CITY INTERNATIONAL AIRPORT,921
13,CHARLOTTE/DOUGLAS INTERNATIONAL AIRPORT,917
14,CINCINNATI/NORTHERN KENTUCKY INTERNATIONAL AIR...,915
15,LOUISVILLE INTERNATIONAL AIRPORT,914
16,ATLANTA INTERNATIONAL AIRPORT,897
17,NEWARK LIBERTY INTERNATIONAL AIRPORT,880
18,ORLANDO INTERNATIONAL AIRPORT,855
19,DENVER INTERNATIONAL AIRPORT,845
20,WASHINGTON DULLES INTERNATIONAL AIRPORT,826
21,METROPOLITAN OAKLAND INTERNATIONAL AIRPORT,775
22,CHICAGO O'HARE INTERNATIONAL AIRPORT,752
23,CLEVELAND-HOPKINS INTERNATIONAL AIRPORT,742
24,HARRISBURG INTERNATIONAL AIRPORT,731
25,LAMBERT-ST LOUIS INTERNATIONAL AIRPORT,659
26,DETROIT METROPOLITAN WAYNE COUNTY AIRPORT,626
27,GREATER PITTSBURGH AIRPORT,623
28,LIHUE AIRPORT,613
29,BIRMINGHAM-SHUTTLESWORTH INTERNATIONAL AIRPORT,605
30,CHICAGO MIDWAY INTERNATIONAL AIRPORT,578
31,EPPLEY AIRFIELD AIRPORT,571
32,RONALD REAGAN WASHINGTON NATIONAL AIRPORT,559
33,MINNEAPOLIS-ST PAUL INTERNATIONAL AIRPORT,557
34,SIMON BOLIVAR AIRPORT,542
35,LOS ANGELES INTERNATIONAL AIRPORT,530
36,MEMPHIS INTERNATIONAL AIRPORT,514
37,PORTLAND INTERNATIONAL (OR) AIRPORT,508

In [95]:
#Getting the airport coordinates for '500 to 1000 strikes' data using the geocoding function

lat_500to1000, long_500to1000 = get_coordinates(strikes500to1000['Airport: Name'])

In [97]:
#Adding the obtained coordinates to the dataframe by creating new columns for latitudes and longitudes

strikes500to1000.loc[:, 'latitude'] = lat_500to1000
strikes500to1000.loc[:, 'longitude'] = long_500to1000

In [100]:
strikes500to1000

,Airport: Name,Wildlife: Number Struck Actual,latitude,longitude
11,LOGAN INTERNATIONAL AIRPORT,962,42.363177,-71.013640
12,KANSAS CITY INTERNATIONAL AIRPORT,921,39.302310,-94.721190
13,CHARLOTTE/DOUGLAS INTERNATIONAL AIRPORT,917,35.210741,-80.945744
14,CINCINNATI/NORTHERN KENTUCKY INTERNATIONAL AIR...,915,39.049906,-84.665157
15,LOUISVILLE INTERNATIONAL AIRPORT,914,38.186699,-85.741417
16,ATLANTA INTERNATIONAL AIRPORT,897,33.637401,-84.429816
17,NEWARK LIBERTY INTERNATIONAL AIRPORT,880,40.689064,-74.177255
18,ORLANDO INTERNATIONAL AIRPORT,855,28.412904,-81.309443
19,DENVER INTERNATIONAL AIRPORT,845,39.860668,-104.685367
20,WASHINGTON DULLES INTERNATIONAL AIRPORT,826,38.952266,-77.453485
21,METROPOLITAN OAKLAND INTERNATIONAL AIRPORT,775,37.722259,-122.217017
22,CHICAGO O'HARE INTERNATIONAL AIRPORT,752,41.978081,-87.909182
23,CLEVELAND-HOPKINS INTERNATIONAL AIRPORT,742,41.406454,-81.851101
24,HARRISBURG INTERNATIONAL AIRPORT,731,40.193210,-76.752946
25,LAMBERT-ST LOUIS INTERNATIONAL AIRPORT,659,38.749627,-90.370470
26,DETROIT METROPOLITAN WAYNE COUNTY AIRPORT,626,42.205699,-83.352975
27,GREATER PITTSBURGH AIRPORT,623,40.491783,-80.237024
28,LIHUE AIRPORT,613,21.972066,-159.336715
29,BIRMINGHAM-SHUTTLESWORTH INTERNATIONAL AIRPORT,605,33.563496,-86.751527
30,CHICAGO MIDWAY INTERNATIONAL AIRPORT,578,41.785514,-87.751724
31,EPPLEY AIRFIELD AIRPORT,571,41.301125,-95.889871
32,RONALD REAGAN WASHINGTON NATIONAL AIRPORT,559,38.851289,-77.039689
33,MINNEAPOLIS-ST PAUL INTERNATIONAL AIRPORT,557,44.878019,-93.220928
34,SIMON BOLIVAR AIRPORT,542,10.603162,-66.996677
35,LOS ANGELES INTERNATIONAL AIRPORT,530,33.942168,-118.421359
36,MEMPHIS INTERNATIONAL AIRPORT,514,35.046256,-89.976895
37,PORTLAND INTERNATIONAL (OR) AIRPORT,508,45.587561,-122.593058

In [101]:
#Saving the '500 to 1000 strikes' data as MS Excel file

strikes500to1000.to_excel(r"F:\UM Internship\Bird Strikes Visualization\500to1000Strikes.xlsx")

In [107]:
#Filtering the '10 and above strikes' dataframe to get airports with 300 to 500 bird strikes

strikes300to500 = TenAndAboveStrikes[(TenAndAboveStrikes['Wildlife: Number Struck Actual'] >= 300) & (TenAndAboveStrikes['Wildlife: Number Struck Actual'] < 500)]

In [108]:
strikes300to500

,Airport: Name,Wildlife: Number Struck Actual
38,FORT LAUDERDALE/HOLLYWOOD INTERNATIONAL AIRPORT,481
39,BUFFALO-NIAGARA INTERNATIONAL AIRPORT,474
40,HILO INTERNATIONAL AIRPORT,466
41,GEORGE BUSH INTERCONTINENTAL AIRPORT,460
42,TETERBORO AIRPORT,455
43,NEW ORLEANS INTERNATIONAL AIRPORT,453
44,HONOLULU INTERNATIONAL AIRPORT,445
45,PORT COLUMBUS INTERNATIONAL AIRPORT,431
46,HOUSTON-HOBBY AIRPORT,421
47,AUSTIN-BERGSTROM INTERNATIONAL AIRPORT,417
48,DALLAS LOVE FIELD AIRPORT,409
49,BRADLEY INTERNATIONAL AIRPORT,404
50,INDIANAPOLIS INTERNATIONAL AIRPORT,402
51,RALEIGH-DURHAM INTERNATIONAL AIRPORT,400
52,THEODORE FRANCIS GREEN STATE AIRPORT,388
53,WESTCHESTER COUNTY AIRPORT,366
54,SOUTHWEST FLORIDA INTERNATIONAL AIRPORT,360
55,MIAMI INTERNATIONAL AIRPORT,359
56,ORLANDO SANFORD INTERNATIONAL AIRPORT,349
57,NEW CASTLE COUNTY AIRPORT,346
58,SAVANNAH INTERNATIONAL AIRPORT,341
59,ADAMS FIELD AIRPORT,333
60,QUAD CITY AIRPORT,326
61,MINETA SAN JOSE INTERNATIONAL AIRPORT,315
62,SAN ANTONIO INTERNATIONAL AIRPORT,308
63,BOB HOPE AIRPORT,300

In [109]:
#Getting the airport coordinates for '300 to 500 strikes' data using the geocoding function

lat_300to500, long_300to500 = get_coordinates(strikes300to500['Airport: Name'])

In [112]:
#Adding the obtained coordinates to the dataframe by creating new columns for latitudes and longitudes

strikes300to500.loc[:, 'latitude'] = lat_300to500
strikes300to500.loc[:, 'longitude'] = long_300to500

In [115]:
strikes300to500

,Airport: Name,Wildlife: Number Struck Actual,latitude,longitude
38,FORT LAUDERDALE/HOLLYWOOD INTERNATIONAL AIRPORT,481,26.072017,-80.150997
39,BUFFALO-NIAGARA INTERNATIONAL AIRPORT,474,42.940202,-78.730752
40,HILO INTERNATIONAL AIRPORT,466,19.718831,-155.047554
41,GEORGE BUSH INTERCONTINENTAL AIRPORT,460,29.984142,-95.332986
42,TETERBORO AIRPORT,455,40.849510,-74.063536
43,NEW ORLEANS INTERNATIONAL AIRPORT,453,29.994200,-90.264304
44,HONOLULU INTERNATIONAL AIRPORT,445,21.321157,-157.918442
45,PORT COLUMBUS INTERNATIONAL AIRPORT,431,39.997056,-82.893041
46,HOUSTON-HOBBY AIRPORT,421,29.647149,-95.276930
47,AUSTIN-BERGSTROM INTERNATIONAL AIRPORT,417,30.193489,-97.665010
48,DALLAS LOVE FIELD AIRPORT,409,32.845241,-96.847322
49,BRADLEY INTERNATIONAL AIRPORT,404,41.940584,-72.685020
50,INDIANAPOLIS INTERNATIONAL AIRPORT,402,39.716253,-86.295084
51,RALEIGH-DURHAM INTERNATIONAL AIRPORT,400,35.880361,-78.787238
52,THEODORE FRANCIS GREEN STATE AIRPORT,388,41.722440,-71.428588
53,WESTCHESTER COUNTY AIRPORT,366,41.068017,-73.708333
54,SOUTHWEST FLORIDA INTERNATIONAL AIRPORT,360,26.532950,-81.758806
55,MIAMI INTERNATIONAL AIRPORT,359,25.794979,-80.286723
56,ORLANDO SANFORD INTERNATIONAL AIRPORT,349,28.775952,-81.241239
57,NEW CASTLE COUNTY AIRPORT,346,39.679671,-75.607634
58,SAVANNAH INTERNATIONAL AIRPORT,341,32.124238,-81.197706
59,ADAMS FIELD AIRPORT,333,34.731109,-92.224578
60,QUAD CITY AIRPORT,326,41.447721,-90.511467
61,MINETA SAN JOSE INTERNATIONAL AIRPORT,315,37.363330,-121.929337
62,SAN ANTONIO INTERNATIONAL AIRPORT,308,29.533402,-98.469214
63,BOB HOPE AIRPORT,300,34.203173,-118.359178

In [116]:
#Saving the '300 to 500 strikes' data as MS Excel file

strikes300to500.to_excel(r"F:\UM Internship\Bird Strikes Visualization\300to500Strikes.xlsx")

In [120]:
#Filtering the '10 and above strikes' dataframe to get airports with 200 to 300 bird strikes

strikes200to300 = TenAndAboveStrikes[(TenAndAboveStrikes['Wildlife: Number Struck Actual'] >= 200) & (TenAndAboveStrikes['Wildlife: Number Struck Actual'] < 300)]

In [121]:
strikes200to300

,Airport: Name,Wildlife: Number Struck Actual
64,TAMPA INTERNATIONAL AIRPORT,288
65,PHOENIX SKY HARBOR AIRPORT,288
66,ALBANY INTERNATIONAL AIRPORT,284
67,LAKEFRONT AIRPORT,283
68,GERALD R FORD INTERNATIONAL AIRPORT,277
69,LONG ISLAND MAC ARTHUR AIRPORT,270
70,DES MOINES INTERNATIONAL AIRPORT,269
71,NEWPORT NEWS/WILLIAMSBURG INTERNATIONAL AIRPORT,268
72,GROTON-NEW LONDON AR AIRPORT,265
73,ONTARIO INTERNATIONAL AIRPORT,265
74,KAHULUI AIRPORT,257
75,BURKE LAKEFRONT AIRPORT,251
76,JACKSONVILLE INTERNATIONAL AIRPORT,237
77,MANCHESTER AIRPORT,227
78,LEHIGH VALLEY INTERNATIONAL AIRPORT,207
79,GENERAL MITCHELL INTERNATIONAL AIRPORT,207
80,MORRISTOWN MUNICIPAL AIRPORT,200

In [124]:
#Cleaning airport names for successful geocoding

strikes200to300.loc[69, 'Airport: Name'] = strikes200to300.loc[69, 'Airport: Name'].replace('MAC ', 'MAC')
strikes200to300.loc[72, 'Airport: Name'] = strikes200to300.loc[72, 'Airport: Name'].replace('AR ', '')

In [126]:
strikes200to300

,Airport: Name,Wildlife: Number Struck Actual
64,TAMPA INTERNATIONAL AIRPORT,288
65,PHOENIX SKY HARBOR AIRPORT,288
66,ALBANY INTERNATIONAL AIRPORT,284
67,LAKEFRONT AIRPORT,283
68,GERALD R FORD INTERNATIONAL AIRPORT,277
69,LONG ISLAND MACARTHUR AIRPORT,270
70,DES MOINES INTERNATIONAL AIRPORT,269
71,NEWPORT NEWS/WILLIAMSBURG INTERNATIONAL AIRPORT,268
72,GROTON-NEW LONDON AIRPORT,265
73,ONTARIO INTERNATIONAL AIRPORT,265
74,KAHULUI AIRPORT,257
75,BURKE LAKEFRONT AIRPORT,251
76,JACKSONVILLE INTERNATIONAL AIRPORT,237
77,MANCHESTER AIRPORT,227
78,LEHIGH VALLEY INTERNATIONAL AIRPORT,207
79,GENERAL MITCHELL INTERNATIONAL AIRPORT,207
80,MORRISTOWN MUNICIPAL AIRPORT,200

In [127]:
#Getting the airport coordinates for '200 to 300 strikes' data using the geocoding function

lat_200to300, long_200to300 = get_coordinates(strikes200to300['Airport: Name'])

In [130]:
#Adding the obtained coordinates to the dataframe by creating new columns for latitudes and longitudes

strikes200to300.loc[:, 'latitude'] = lat_200to300
strikes200to300.loc[:, 'longitude'] = long_200to300

In [133]:
strikes200to300

,Airport: Name,Wildlife: Number Struck Actual,latitude,longitude
64,TAMPA INTERNATIONAL AIRPORT,288,27.979165,-82.534928
65,PHOENIX SKY HARBOR AIRPORT,288,33.432849,-112.006791
66,ALBANY INTERNATIONAL AIRPORT,284,42.748016,-73.798556
67,LAKEFRONT AIRPORT,283,41.518817,-81.681132
68,GERALD R FORD INTERNATIONAL AIRPORT,277,42.876610,-85.536291
69,LONG ISLAND MACARTHUR AIRPORT,270,40.795809,-73.099201
70,DES MOINES INTERNATIONAL AIRPORT,269,41.534549,-93.659239
71,NEWPORT NEWS/WILLIAMSBURG INTERNATIONAL AIRPORT,268,37.133394,-76.507349
72,GROTON-NEW LONDON AIRPORT,265,41.330529,-72.046506
73,ONTARIO INTERNATIONAL AIRPORT,265,34.054142,-117.599158
74,KAHULUI AIRPORT,257,20.895698,-156.434048
75,BURKE LAKEFRONT AIRPORT,251,41.518817,-81.681132
76,JACKSONVILLE INTERNATIONAL AIRPORT,237,30.493750,-81.693038
77,MANCHESTER AIRPORT,227,53.350342,-2.280369
78,LEHIGH VALLEY INTERNATIONAL AIRPORT,207,40.651163,-75.442254
79,GENERAL MITCHELL INTERNATIONAL AIRPORT,207,42.946542,-87.897258
80,MORRISTOWN MUNICIPAL AIRPORT,200,40.799808,-74.422509

In [134]:
#Saving the '200 to 300 strikes' data as MS Excel file

strikes200to300.to_excel(r"F:\UM Internship\Bird Strikes Visualization\200to300Strikes.xlsx")

In [140]:
#Filtering the '10 and above strikes' dataframe to get airports with 150 to 200 bird strikes

strikes150to200 = TenAndAboveStrikes[(TenAndAboveStrikes['Wildlife: Number Struck Actual'] >= 150) & (TenAndAboveStrikes['Wildlife: Number Struck Actual'] < 200)]

In [141]:
strikes150to200

                               Airport: Name  Wildlife: Number Struck Actual
81                      LOVELL FIELD AIRPORT                             199
82      CHARLESTON AFB/INTERNATIONAL AIRPORT                             199
83                       NAPA COUNTY AIRPORT                             198
84      SPRINGFIELD-BRANSON NATIONAL AIRPORT                             196
85        COLORADO SPRINGS MUNICIPAL AIRPORT                             190
86           SANTA BARBARA MUNICIPAL AIRPORT                             188
87         UNIV OF ILLINOIS -WILLARD AIRPORT                             187
88                 LINCOLN MUNICIPAL AIRPORT                             183
89                  ROANOKE REGIONAL AIRPORT                             180
90                          EL MONTE AIRPORT                             174
91               TULSA INTERNATIONAL AIRPORT                             174
92                  AIRBORNE AIRPARK AIRPORT                             170
93   GREATER ROCHESTER INTERNATIONAL AIRPORT                             165
94          GULFPORT BILOXI REGIONAL AIRPORT                             163
95                      GRANT COUNTY AIRPORT                             161
96               EVANSVILLE REGIONAL AIRPORT                             160
97             SITKA ROCKY GUTIERREZ AIRPORT                             157
98                            DUPAGE AIRPORT                             156
99         ALBUQUERQUE INTERNATIONAL AIRPORT                             156
100                 GREATER ROCKFORD AIRPORT                             156
101             LONG BEACH-DAUGH FLD AIRPORT                             150

In [144]:
#Cleaning airport names for successful geocoding

strikes150to200.loc[82, 'Airport: Name'] = strikes150to200.loc[82, 'Airport: Name'].replace('AFB/', '')
strikes150to200.loc[90, 'Airport: Name'] = strikes150to200.loc[90, 'Airport: Name'].replace('EL MONTE', 'SAN GABRIEL VALLEY')
strikes150to200.loc[100, 'Airport: Name'] = strikes150to200.loc[100, 'Airport: Name'].replace('GREATER', 'CHICAGO').replace('AIRPORT', 'INTERNATIONAL AIRPORT')
strikes150to200.loc[101, 'Airport: Name'] = strikes150to200.loc[101, 'Airport: Name'].replace('-DAUGH FLD', '')

In [148]:
strikes150to200

                               Airport: Name  Wildlife: Number Struck Actual
81                      LOVELL FIELD AIRPORT                             199
82          CHARLESTON INTERNATIONAL AIRPORT                             199
83                       NAPA COUNTY AIRPORT                             198
84      SPRINGFIELD-BRANSON NATIONAL AIRPORT                             196
85        COLORADO SPRINGS MUNICIPAL AIRPORT                             190
86           SANTA BARBARA MUNICIPAL AIRPORT                             188
87         UNIV OF ILLINOIS -WILLARD AIRPORT                             187
88                 LINCOLN MUNICIPAL AIRPORT                             183
89                  ROANOKE REGIONAL AIRPORT                             180
90                SAN GABRIEL VALLEY AIRPORT                             174
91               TULSA INTERNATIONAL AIRPORT                             174
92                  AIRBORNE AIRPARK AIRPORT                             170
93   GREATER ROCHESTER INTERNATIONAL AIRPORT                             165
94          GULFPORT BILOXI REGIONAL AIRPORT                             163
95                      GRANT COUNTY AIRPORT                             161
96               EVANSVILLE REGIONAL AIRPORT                             160
97             SITKA ROCKY GUTIERREZ AIRPORT                             157
98                            DUPAGE AIRPORT                             156
99         ALBUQUERQUE INTERNATIONAL AIRPORT                             156
100   CHICAGO ROCKFORD INTERNATIONAL AIRPORT                             156
101                       LONG BEACH AIRPORT                             150

In [149]:
#Getting the airport coordinates for '150 to 200 strikes' data using the geocoding function

lat_150to200, long_150to200 = get_coordinates(strikes150to200['Airport: Name'])

In [152]:
#Adding the obtained coordinates to the dataframe by creating new columns for latitudes and longitudes

strikes150to200.loc[:, 'latitude'] = lat_150to200
strikes150to200.loc[:, 'longitude'] = long_150to200

In [155]:
strikes150to200

,Airport: Name,Wildlife: Number Struck Actual,latitude,longitude
81,LOVELL FIELD AIRPORT,199,35.032384,-85.201678
82,CHARLESTON INTERNATIONAL AIRPORT,199,32.899298,-80.039465
83,NAPA COUNTY AIRPORT,198,38.216488,-122.276571
84,SPRINGFIELD-BRANSON NATIONAL AIRPORT,196,37.242984,-93.388914
85,COLORADO SPRINGS MUNICIPAL AIRPORT,190,38.800430,-104.703277
86,SANTA BARBARA MUNICIPAL AIRPORT,188,34.427430,-119.843140
87,UNIV OF ILLINOIS -WILLARD AIRPORT,187,40.038317,-88.271567
88,LINCOLN MUNICIPAL AIRPORT,183,40.847315,-96.757443
89,ROANOKE REGIONAL AIRPORT,180,37.324426,-79.976797
90,SAN GABRIEL VALLEY AIRPORT,174,34.086202,-118.032980
91,TULSA INTERNATIONAL AIRPORT,174,36.201023,-95.886813
92,AIRBORNE AIRPARK AIRPORT,170,39.429955,-83.791964
93,GREATER ROCHESTER INTERNATIONAL AIRPORT,165,43.116170,-77.672693
94,GULFPORT BILOXI REGIONAL AIRPORT,163,30.410661,-89.059461
95,GRANT COUNTY AIRPORT,161,32.638452,-108.152735
96,EVANSVILLE REGIONAL AIRPORT,160,38.041888,-87.529684
97,SITKA ROCKY GUTIERREZ AIRPORT,157,57.047956,-135.363585
98,DUPAGE AIRPORT,156,41.905135,-88.252183
99,ALBUQUERQUE INTERNATIONAL AIRPORT,156,35.037669,-106.610968
100,CHICAGO ROCKFORD INTERNATIONAL AIRPORT,156,42.196620,-89.101859
101,LONG BEACH AIRPORT,150,33.815566,-118.153429

In [156]:
#Saving the '150 to 200 strikes' data as MS Excel file

strikes150to200.to_excel(r"F:\UM Internship\Bird Strikes Visualization\150to200Strikes.xlsx")

In [159]:
#Filtering the '10 and above strikes' dataframe to get airports with 100 to 150 bird strikes

strikes100to150 = TenAndAboveStrikes[(TenAndAboveStrikes['Wildlife: Number Struck Actual'] >= 100) & (TenAndAboveStrikes['Wildlife: Number Struck Actual'] < 150)]

In [160]:
strikes100to150

,Airport: Name,Wildlife: Number Struck Actual
102,WICHITA MID-CONTINENT AIRPORT,145
103,PENSACOLA REGIONAL AIRPORT,143
104,OUTAGAMIE COUNTY REGIONAL AIRPORT,142
105,DANE COUNTY REGIONAL AIRPORT-TRUAX FLD,141
106,SAN DIEGO INTERNATIONAL AIRPORT,138
107,SKYLARK FIELD AIRPORT,135
108,ST AUGUSTINE AIRPORT,133
109,MCCARREN INTERNATIONAL AIRPORT,128
110,KAPALUA AIRPORT,128
111,ATLANTIC CITY INTERNATIONAL AIRPORT,127
112,BUSH FLD AIRPORT,122
113,JAMES M COX DAYTON INTERNATIONAL AIRPORT,122
114,WILKES-BARRE/SCRANTON INTERNATIONAL AIRPORT,121
115,MYRTLE BEACH INTERNATIONAL AIRPORT,121
116,ABRAHAM LINCOLN CAPITAL AIRPORT,119
117,BLUE GRASS AIRPORT,119
118,JACKSON EVERS INTERNATIONAL AIRPORT,118
119,RICHMOND INTERNATIONAL AIRPORT,117
120,BOWERMAN AIRPORT,113
121,CAPITAL CITY AIRPORT (PA),113
122,MOLOKAI AIRPORT,112
123,LEWISTON-NEZ PERCE CO AIRPORT,111
124,BARKSDALE AIR FORCE BASE AIRPORT,111
125,PALM BEACH INTERNATIONAL AIRPORT,109
126,VAN NUYS AIRPORT,109
127,LUIS MUNOZ MARIN INTERNATIONAL -SAN JUAN AIRPORT,109
128,JOHN WAYNE AIRPORT,107
129,ALLEGHENY COUNTY AIRPORT,107
130,RENO TAHOE INTERNATIONAL AIRPORT,107
131,WILMINGTON INTERNATIONAL AIRPORT,107
132,PANAMA CITY - BAY COUNTY INTERNATIONAL AIRPORT,106
133,EL PASO INTERNATIONAL AIRPORT,106
134,WILL ROGERS WORLD AIRPORT,105
135,DAYTONA BEACH INTERNATIONAL AIRPORT,103
136,ADDISON AIRPORT,101
137,BATON ROUGE METRO AIRPORT,100

In [163]:
#Cleaning airport names for successful geocoding

strikes100to150.loc[105, 'Airport: Name'] = strikes100to150.loc[105, 'Airport: Name'].replace('-TRUAX FLD', '')
strikes100to150.loc[109, 'Airport: Name'] = strikes100to150.loc[109, 'Airport: Name'].replace('MCCARREN', 'MCCARRAN')
strikes100to150.loc[112, 'Airport: Name'] = strikes100to150.loc[112, 'Airport: Name'].replace('BUSH FLD', 'AUGUSTA REGIONAL')
strikes100to150.loc[124, 'Airport: Name'] = strikes100to150.loc[124, 'Airport: Name'].replace(' AIRPORT', '')
strikes100to150.loc[127, 'Airport: Name'] = strikes100to150.loc[127, 'Airport: Name'].replace(' -SAN JUAN', '')
strikes100to150.loc[132, 'Airport: Name'] = strikes100to150.loc[132, 'Airport: Name'].replace('PANAMA CITY - BAY COUNTY', 'NORTHWEST FLORIDA BEACHES')
strikes100to150.loc[137, 'Airport: Name'] = strikes100to150.loc[137, 'Airport: Name'].replace('METRO', 'METROPOLITAN')

In [170]:
strikes100to150

,Airport: Name,Wildlife: Number Struck Actual
102,WICHITA MID-CONTINENT AIRPORT,145
103,PENSACOLA REGIONAL AIRPORT,143
104,OUTAGAMIE COUNTY REGIONAL AIRPORT,142
105,DANE COUNTY REGIONAL AIRPORT,141
106,SAN DIEGO INTERNATIONAL AIRPORT,138
107,SKYLARK FIELD AIRPORT,135
108,ST AUGUSTINE AIRPORT,133
109,MCCARRAN INTERNATIONAL AIRPORT,128
110,KAPALUA AIRPORT,128
111,ATLANTIC CITY INTERNATIONAL AIRPORT,127
112,AUGUSTA REGIONAL AIRPORT,122
113,JAMES M COX DAYTON INTERNATIONAL AIRPORT,122
114,WILKES-BARRE/SCRANTON INTERNATIONAL AIRPORT,121
115,MYRTLE BEACH INTERNATIONAL AIRPORT,121
116,ABRAHAM LINCOLN CAPITAL AIRPORT,119
117,BLUE GRASS AIRPORT,119
118,JACKSON EVERS INTERNATIONAL AIRPORT,118
119,RICHMOND INTERNATIONAL AIRPORT,117
120,BOWERMAN AIRPORT,113
121,CAPITAL CITY AIRPORT (PA),113
122,MOLOKAI AIRPORT,112
123,LEWISTON-NEZ PERCE CO AIRPORT,111
124,BARKSDALE AIR FORCE BASE,111
125,PALM BEACH INTERNATIONAL AIRPORT,109
126,VAN NUYS AIRPORT,109
127,LUIS MUNOZ MARIN INTERNATIONAL AIRPORT,109
128,JOHN WAYNE AIRPORT,107
129,ALLEGHENY COUNTY AIRPORT,107
130,RENO TAHOE INTERNATIONAL AIRPORT,107
131,WILMINGTON INTERNATIONAL AIRPORT,107
132,NORTHWEST FLORIDA BEACHES INTERNATIONAL AIRPORT,106
133,EL PASO INTERNATIONAL AIRPORT,106
134,WILL ROGERS WORLD AIRPORT,105
135,DAYTONA BEACH INTERNATIONAL AIRPORT,103
136,ADDISON AIRPORT,101
137,BATON ROUGE METROPOLITAN AIRPORT,100

In [171]:
#Getting the airport coordinates for '100 to 150 strikes' data using the geocoding function

lat_100to150, long_100to150 = get_coordinates(strikes100to150['Airport: Name'])

In [174]:
#Adding the obtained coordinates to the dataframe by creating new columns for latitudes and longitudes

strikes100to150.loc[:, 'latitude'] = lat_100to150
strikes100to150.loc[:, 'longitude'] = long_100to150

In [177]:
strikes100to150

,Airport: Name,Wildlife: Number Struck Actual,latitude,longitude
102,WICHITA MID-CONTINENT AIRPORT,145,37.649253,-97.432263
103,PENSACOLA REGIONAL AIRPORT,143,30.472597,-87.188086
104,OUTAGAMIE COUNTY REGIONAL AIRPORT,142,44.256595,-88.521696
105,DANE COUNTY REGIONAL AIRPORT,141,43.142082,-89.337745
106,SAN DIEGO INTERNATIONAL AIRPORT,138,32.733361,-117.192246
107,SKYLARK FIELD AIRPORT,135,33.627814,-117.300922
108,ST AUGUSTINE AIRPORT,133,12.499093,124.638566
109,MCCARRAN INTERNATIONAL AIRPORT,128,36.086103,-115.161120
110,KAPALUA AIRPORT,128,20.965573,-156.671565
111,ATLANTIC CITY INTERNATIONAL AIRPORT,127,39.457085,-74.570276
112,AUGUSTA REGIONAL AIRPORT,122,33.372302,-81.965064
113,JAMES M COX DAYTON INTERNATIONAL AIRPORT,122,39.905319,-84.220245
114,WILKES-BARRE/SCRANTON INTERNATIONAL AIRPORT,121,41.337092,-75.722571
115,MYRTLE BEACH INTERNATIONAL AIRPORT,121,33.680641,-78.929060
116,ABRAHAM LINCOLN CAPITAL AIRPORT,119,39.843686,-89.679566
117,BLUE GRASS AIRPORT,119,38.034804,-84.604922
118,JACKSON EVERS INTERNATIONAL AIRPORT,118,32.312110,-90.076778
119,RICHMOND INTERNATIONAL AIRPORT,117,37.506967,-77.321484
120,BOWERMAN AIRPORT,113,46.971943,-123.936090
121,CAPITAL CITY AIRPORT (PA),113,40.216752,-76.853172
122,MOLOKAI AIRPORT,112,21.152645,-157.096216
123,LEWISTON-NEZ PERCE CO AIRPORT,111,46.375731,-117.015503
124,BARKSDALE AIR FORCE BASE,111,32.497523,-93.610843
125,PALM BEACH INTERNATIONAL AIRPORT,109,26.685948,-80.092487
126,VAN NUYS AIRPORT,109,34.207209,-118.490148
127,LUIS MUNOZ MARIN INTERNATIONAL AIRPORT,109,18.443199,-65.997430
128,JOHN WAYNE AIRPORT,107,33.674205,-117.868024
129,ALLEGHENY COUNTY AIRPORT,107,40.353445,-79.929047
130,RENO TAHOE INTERNATIONAL AIRPORT,107,39.498646,-119.773332
131,WILMINGTON INTERNATIONAL AIRPORT,107,34.273536,-77.909535
132,NORTHWEST FLORIDA BEACHES INTERNATIONAL AIRPORT,106,30.359931,-85.804046
133,EL PASO INTERNATIONAL AIRPORT,106,31.809584,-106.366598
134,WILL ROGERS WORLD AIRPORT,105,35.395548,-97.596226
135,DAYTONA BEACH INTERNATIONAL AIRPORT,103,29.181644,-81.054269
136,ADDISON AIRPORT,101,32.969999,-96.836677
137,BATON ROUGE METROPOLITAN AIRPORT,100,30.531974,-91.150424

In [178]:
#Saving the '100 to 150 strikes' data as MS Excel file

strikes100to150.to_excel(r"F:\UM Internship\Bird Strikes Visualization\100to150Strikes.xlsx")